### ISSUE TITLE
Recent tab is showing the incorrect file name

### ISSUE THREAD

**Issue by jacksonv1lle** [OneDrive/samples#12]
**Describe the bug**
When using the OneDrive File Picker, the files which are displayed in the **Recent** tab are using the wrong file name in certain cases. 

**To Reproduce**
- Open the OneDrive File Picker in the **Recent** tab
- Identify a docx file already in the Recent tab which is hosted in a SharePoint document library
- Navigate to that file in the document library
- If the file does not have the **Title** property set then set the value to something like: `test`
- Now rename the file in the document library (eg. append a '1' to the file name)
- Wait for 1 - 5 minutes. Not sure how long it takes for this change to propagate to the ODFP
- Open the OneDrive File Picker in the `Recent` tab again
- Notice that the name of the file is now `test.docx`

**Expected behavior**
After changing the name of the file, I would expect the new file name to be displayed in the Recent tab (not the file title with .docx at the end).

**Screenshots**
![onedrive-file-picker_screenshots](https://user-images.githubusercontent.com/2648490/182858767-14714e3d-dc85-436d-91b4-162beffdf8e1.png)

**Details**
This seems to happen only after the filename has been changed and the file has the **Title** property set. If the Title property is not set, then the new filename appears correctly in the Recent tab.

This bug does not occur when you locate the file from the Quick access tab - Only in the Recent tab

**Comment by ntennant4** [comment]
Thanks for submitting, reviewing this one and will get back to you once we have a repro/answer for what's causing this.

**Comment by JCrew0** [comment]
@jacksonv1lle and @ntennant4 I'm going through and cleaning up some of the issues here. Was this resolved?

**Comment by jacksonv1lle** [comment]
Sorry I haven't checked back into this bug in a while.

The bug is still there although the title is updated after selecting the row item.


https://github.com/OneDrive/samples/assets/2648490/276608b2-163b-4069-9401-11b49ac8e368

Seems to me that the `_api/v2.0/drives/me/recent` endpoint is returning the wrong name value.

![image](https://github.com/OneDrive/samples/assets/2648490/d03a1f3a-1c70-462a-b9f8-c1b889cf3597)
