### ISSUE TITLE
File Picker 8.0 is not working in iframe, contrary to the statement in the documentation.

### ISSUE THREAD

**Issue by boraunlu** [OneDrive/samples#16]
#### Category
- [ ] Question
- [x] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

According to the documentation [here](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/?view=odsp-graph-online), File Picker 8.0 supports being hosted in an iframe. The sentence goes "The page can be hosted either embedded in an iframe or as a popup."

#### Observed Behavior

When being attached into the frame, the picker refuses to connect and throws out this error:
Refused to frame 'https://{{company}}-my.sharepoint.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' teams.microsoft.com *.teams.microsoft.com *.skype.com *.teams.microsoft.us local.teams.office.com *.powerapps.com *.yammer.com *.officeapps.live.com *.office.com *.stream.azure-test.net *.microsoftstream.com *.dynamics.com *.microsoft.com".

Is it possible to embed this picker in an iframe in a non-Microsoft website?

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
