### ISSUE TITLE
Does Filepicker v8.0 support search? 

### ISSUE THREAD

**Issue by capedrolima** [OneDrive/samples#20]
Hi guys,
We are implementing the OneDrive File Picker. It's looking good, but some of our clients need the possibility of searching for files thru FilePicker. 

I'm still determining if I missed something here, but I didn't find that option. Is this something that can be done?

**Comment by patrick-rodgers** [comment]
Not currently, no. Within the service the control is designed for browsing specific sites/libraries so does not include search capabilities. Thanks for the feedback, will share with engineering team.

**Comment by patrick-rodgers** [comment]
Great news! The ability to enable search in the picker is now available. I've added a [sample config](https://github.com/OneDrive/samples/blob/master/samples/file-picking/example-picker-configs/enable-search.json) to show how.

You need to add the `search` node to the config which is an object with a single property "enabled". Set that to true and you'll have a search bar in your picker.

Here is the example as well for reference:

```JSON
{
    "sdk": "8.0",
    "entry": {
        "oneDrive": {
            "files": {}
        }
    },
    "authentication": {},
    "messaging": {
        "origin": "http://localhost:3000",
        "channelId": "27"
    },
    "typesAndSources": {
        "mode": "files",
        "pivots": {
            "oneDrive": true,
            "recent": true
        }
    },
    "search": {
        "enabled": true
    }
}
```

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
