### ISSUE TITLE
How to find the baseURL

### ISSUE THREAD

**Issue by trickcharan** [OneDrive/samples#21]
Am currently developing an application in which I am hosting the MS V8 file picker. The application is mainly about the file viewer, any person with an Org account or Personal account can view or download their files. While implementing I was facing an issue, The issue is I have hard-coded a particular baseURL to load the v8 picker for testing (Test environment). But in production different org people or personal users may log in, So how do I find out the baseURL for that user? Also from the previous issues, I understood that the v8 picker won’t support the graph APIs. So is there any workaround that I can fetch the baseURL before login?

FYI: Also we cannot ask users for their tenant URL every time when they log in. Because the same user can have both personal and org login.

**Comment by patrick-rodgers** [comment]
Is my understanding correct that you have a user authenticated against some AAD instance? If so you can make any graph calls you want OBO that user, for example to get the url of a user's main OneDrive you can use `https://graph.microsoft.com/v1.0/me/drive` and parse the webUrl property.

For referencing a SharePoint site, you'd likely already need to know what site/library you wanted to explorer. You could possibly use the `https://graph.microsoft.com/v1.0/me/followedSites` call for sites that user follows.

In general, the picker works in the context of already knowing the resource you want to browse.

**Comment by trickcharan** [comment]
Nope, I don't have any users authenticated with any AAD instance. Even if I authenticate the user with any graph scope, the same access token is not working with the v8 picker.  
 FYI: Am not using msal library mentioned in the sample (const app = new msal.PublicClientApplication(msalParams);) to log in, Instead am creating the auth token separately using postman and pasting the access token in the sample.

**Comment by patrick-rodgers** [comment]
Correct, the same access token would not work, they are different resources. You would need a token targeting SharePoing as shown in all the examples. If you don't have an authenticated AAD user or even a session the picker won't work with a pasted in graph token. Is there a reason you aren't running the samples (which include auth code) as described?

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
