### ISSUE TITLE
Basic JS Sample not working with https://xxxx.sharepoint.com and https://xxx-my.sharepoint.com at the same time

### ISSUE THREAD

**Issue by capedrolima** [OneDrive/samples#22]
Hi guys, 
We are using the basic javascript samples provided, but we have the same problem described in [ticket 7](https://github.com/OneDrive/samples/issues/7)

We aim to make it possible for the user to select files/folders from both places (Recent, My Files, QuickAccess-Sharepoint). But it looks like we need to manage different tokens. Right now, as a workaround, we have two starting point URLs.

- https://wdxxxxxxxxt-my.sharepoint.com/_layouts/15/FilePicker.aspx?
- https://wdxxxxxxxxt-sharepoint.com/_layouts/15/FilePicker.aspx

![FilePicker-my sharepoint](https://user-images.githubusercontent.com/50597814/204860136-57e25604-1c03-49d3-80be-1b1376cd14e8.gif)

Some of you can help us to make the basic javascript sample works with both scenarios? I'm not sure if @patrick-rodgers already spoke with the team about it.

**Historical information from [ticket 7]**
 Glad you got it working, we'll have to review the demo code and see what might be wrong there. Thanks!
_Originally posted by @patrick-rodgers  in https://github.com/OneDrive/samples/issues/7#issuecomment-1179221122_

Thanks in advance, the feature is really helpful.

**Comment by patrick-rodgers** [comment]
Sorry - not sure what you are asking for. The picker is meant to per instance target one location or the other. Hence the baseUrl value which is used to load it in the service. You would need to manage different tokens as they are different resource (my vs sp). Can you explain a bit more on what you are looking to enable?

**Comment by capedrolima** [comment]
Hi Patrick, thanks for your explanation and sorry for the misunderstanding. We were able to manage the different tokens internally. Thanks again!

**Comment by patrick-rodgers** [comment]
Right on, thanks for using the control!
