### ISSUE TITLE
Save Files to One Drive via Modal

### ISSUE THREAD

**Issue by AnkitBajpaii** [OneDrive/samples#23]
I am currently working on a requirement that requires me to implement two things:
1. Users should be able to pick files from their One Drive
2. Users should be able to Save files to their One Drive.

I am able to achieve #1 of requirements with the help of Onedrive File Picker v8 control & I also referred to the samples project.

But for #2 requirement, where users could save files to their OneDrive, I am unable to find a sample reference code. Shall I be using the same File Picker v8 control even for Saving files to One Drive. But then, how can we get rid of the Select & Cancel button and just have the Save button. Is there any separate control that I should be using for Saving Files to One Drive via pop up modal Or is there any one property in file options that I can set.

What i need is a File Upload Modal with Save/Select button ( like how we get in Google Drive when we upload the docs)

I got a reference to this document but it is using old control:
https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/save-file?source=recommendations&view=odsp-graph-online

Is there any similar document to the new Save File control as well.

**Comment by patrick-rodgers** [comment]
If you have `Files.ReadWrite.All` you can upload files through the picker interface, there is a widget that appears in the top of the control. This is something we can add to the docs.

![image](https://user-images.githubusercontent.com/13154702/208120511-37128e6f-22d2-4c8b-b5aa-efce44d62f23.png)

"What i need is a File Upload Modal with Save/Select button" - this would be a different thing, so you're really asking for a new control? You can also [upload files directly](https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http) as an option for building your own modal.

**Comment by AnkitBajpaii** [comment]
Thanks for the reply Patrick.

I have taken a reference from dropbox. I am looking for something similar
to dropbox, the way it offers Saving Files to Dropbox via pop up.
The file I have selected to upload is being shown at the bottom part and
there is a Save button. Once I click on Save, the file gets saved to the
selected folder.

This behaviour is also similar to what Google Drive offers when you try to
Save any file from your smartphone to Drive via the Save to Google Drive
option.
Wondering if we could achieve similar functionality from our custom web
app, when it comes to Saving Files to OneDrive


[image: image.png]


Could you please help me out by suggesting how can we achieve this type of
behaviour when it comes to Save Files to One Drive.


*Thanks and Regards,*

*ANKIT BAJPAI*

*M: +917680069007*

👉 Ankit's LinkedIn Profile <https://www.linkedin.com/in/ankitbajpai19/>

👉 Ankit's GitHub Profile <https://github.com/ankitbajpaii>

**Comment by AnkitBajpaii** [comment]
Hi @patrick-rodgers & Team,
Any update on this issue please.

**Comment by AnkitBajpaii** [comment]
Hi @patrick-rodgers 

I am looking for this functionality in version 8 control:

https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/save-file?view=odsp-graph-online

**Comment by patrick-rodgers** [comment]
Hi @AnkitBajpaii, following up in this, I've added a [sample configuration](https://github.com/OneDrive/samples/blob/master/samples/file-picking/example-picker-configs/saveas-dialog.json) showing how to setup the picker to choose only folders, provide a "save-as" prompt for file name, and change the label of the "select" button. This should come pretty close to meeting your requirements.

```JSON
{
    "sdk": "8.0",
    "entry": {
        "oneDrive": {
            "files": {}
        }
    },
    "authentication": {},
    "messaging": {
        "origin": "http://localhost:3000",
        "channelId": "27"
    },
    "typesAndSources": {
        "mode": "folders",
        "pivots": {
            "oneDrive": true,
            "recent": true
        },
        "filters": ["folder"]
    },
    "tray": {
        "prompt": "save-as",
        "saveAs": {
            "fileName": "test.txt"
        }
    },
    "commands": {
        "pick": {
            "label": "Save As"
        }
    }
}
```

In the entry in the `Items` collection you get back when the "Save As" action is invoked you'll see a new property in the entry providing you the name they entered in the save as textbox.

```JSON
"saveAs": {
    "name": "test.txt"
}
```

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
