### ISSUE TITLE
Authentication Login popup blocked by browser

### ISSUE THREAD

**Issue by chrisbekas** [OneDrive/samples#26]
**Describe the bug**
I'm using the `javascript-basic-consumer` sample project. When first using the file picker, the first popup window is displayed, however the second authentication popup is blocked by the browser.

**Comment by chrisbekas** [comment]
Thanks @patrick-rodgers No enhanced pop-up blocking, just standard browser configuration (checked with Chrome, Firefox and Edge) and running on localhost:3000.

Indeed the console message `Uncaught (in promise) BrowserAuthError: popup_window_error: Error opening popup window. This can happen if you are using IE or if popups are blocked in the browser. Details: BrowserAuthError: empty_window_error: window.open returned null or undefined window object.` refers to the MSAL library but what is the recommended approach when most users will not notice or grant access to popups?

**Comment by patrick-rodgers** [comment]
You can use the redirect flow that will redirect the user. [This article](https://learn.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios) outlines the available options depending on the type of thing you are building. You might consider authenticating them prior to showing the pop-up for the picker so you are ready to provide tokens.

You haven't shared what type of thing you are building so hard to give any specific guidance.

**Comment by chrisbekas** [comment]
Great, thanks for the info @patrick-rodgers. We can authenticate users prior to showing the picker so I guess that overcomes the popup issue.

**Comment by aelliott-atlas** [comment]
The error is still occurring using the `javascript-basic` and `javascript-basic-consumer` sample projects. Has anything changed recently which might cause it to occur again?
