### ISSUE TITLE
Is there any plan for V7 deprecation?

### ISSUE THREAD

**Issue by trickcharan** [OneDrive/samples#28]
First of all, I apologize for asking this particular info here, Because I didn't get any other forum to ask this question.
My question is, is there any plan to deprecate the V7 file picker (Onedrive7.2.js SDK)? Till how long the V7 file picker would be supported? Any tentative date for the V7 stoppage?

**Comment by patrick-rodgers** [comment]
We don't have an end date for v7 picker, however it is no longer being updated and we encourage you to update to the v8 picker as soon as is practical.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
