### ISSUE TITLE
FilePicker v8 using Web instead of SPA AAD Authentication

### ISSUE THREAD

**Issue by damacisaac** [OneDrive/samples#29]
**Describe the bug**
In the [setup instructions](https://learn.microsoft.com/en-gb/onedrive/developer/controls/file-pickers/?view=odsp-graph-online), it says to create a Single-page application registry. We've already integrated the v7 file picker with a Web AAD Application for authentication and would like to re-use this with the new file picker, however we end up with authentication errors if we use the token generated with a Web authentication flow.

Is it possible to use a Web access token to instantiate the v8 file picker?

**To Reproduce**
- Create a Web authentication AAD app.
- Instantiate the v8 file picker, as in the examples in this repo. 
- Use an access token generated from a Web AAD application when the file picker sends the authentication message.

**Expected behavior**
The picker should work using either SPA or Web AAD authentication?

**Screenshots**
<img width="1679" alt="Screenshot 2023-02-15 at 5 06 34 AM" src="https://user-images.githubusercontent.com/3689921/218997374-07d14f74-2bb4-44d0-a57f-e5c66382498d.png">

**Comment by patrick-rodgers** [comment]
The picker should work with any valid MSAL setup that can get tokens for SharePoint. The instructions are specific to getting the samples setup. You can see how we are [configuring MSAL in the sample](https://github.com/OneDrive/samples/blob/master/samples/file-picking/javascript-basic/scripts/auth.js). So our samples likely won't work with other configurations - your application should be able to use whatever it needs.

**Comment by damacisaac** [comment]
@patrick-rodgers thanks for the response. So the issue doesn't seem to be related to the application type.

Next question: 

Our current setup is using the OAuth 2.0 with manually crafted http requests (we're not using MSAL or ADAL). The token we receive through this process works with FilePicker v7 but not with FilePicker v8. Any idea why that would be the case?
