### ISSUE TITLE
Document Sets are not visible when filtering on file extension in typesAndSources in configuration schema

### ISSUE THREAD

**Issue by avirallariva** [OneDrive/samples#30]
Issue: 

A user is required to pick a file of certain extension in the workflow. We pass the extension in the 'filters' parameter  in 'typesAndSources' in the Picker Configuration Schema. The filtering seems to work fine. I receive the files with the required extension and the folders in the Sharepoint site. The issue is that the Document Sets are not visible. This hinders the user to pick files of similar extension in the Document Sets. 

The only possible options we can put in filters is string array with values like:

      - photo
      - video
      - audio
      - folder
      - file
      - extensions prefixed with '.'

Possible Solutions: 
- Treat the shared documents as folders 
- Maybe add another parameter to filter based on the 2 content types, i.e. document sets and folder.
- Add Document Sets in the filters options

Document Reference: 
https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/v8-schema?view=odsp-graph-online

**Comment by patrick-rodgers** [comment]
We will review this request with the engineering team.

**Comment by nicolasiscoding** [comment]
Hi @patrick-rodgers @avirallariva, what was the outcome of this?

**Comment by JCrew0** [comment]
Hey @nicolasiscoding, did you ever get updates on this outside of this thread? If not, I can work with the team to provide some. Thanks!
