### ISSUE TITLE
V8 window is not working as expected in mobile and narrow screen

### ISSUE THREAD

**Issue by trickcharan** [OneDrive/samples#31]
Am trying to load the file picker in the mobile browser, but it is not opening, it shows only the My files, Recent and photo options. When I click on any of the options it stuck there. Sometimes it opens (Dont know in what case it is working). So I decided to change the height and width of the window and end up with the same scenario. For your information, I have attached the video for reference.

https://user-images.githubusercontent.com/29520819/221557402-1228e6d1-0a8a-4d9c-ae3c-08c5949f2fb9.mp4

Also, What am trying is, I need to open the v8 picker on the same screen (Below the launch picker button). But it shows an empty content view and after 40 seconds it shows an error. Attached image below

 
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/29520819/221559400-daed3cb2-5afd-4e99-919d-2779a29dd1f2.png">

**Comment by patrick-rodgers** [comment]
This isn't really enough information to provide meaningful assistance. Have you configured the authentication or have any error messages you can share?

**Comment by trickcharan** [comment]
Yes, The authentication was done from the postman app and obtained the access token. 
For reference am pasting my modified code.
    <html>
        <head>
        <script>
            const baseUrl = 'https://onedrive.live.com/picker'
            const token = 'EwBQA61DBAAUZUYqEwmYbaXIJECvBbNriwl1aGYAAXkgUnXLnwF9E5KXetVjTFrRA8Vnnd1rfBVzd4Q4x+XPmTW/mV+pvSLPDHxr31G5WkN8hbT/TkZFddYx6U1B9R80Xe8b31XXWtz+RuRHDwzG3z7hFbiA3ouEvMiYuY1iVY/Kg/PDCFuR00ZzXl4l9SUWbPRudpPcrjQjqFdITgkR4k+Xcr0I4faT6ivIzME6Tx9ec05S865WqOmSRaofpJCbVE0vq0tTKjBiZmm6NgizGh1WpafGMC9JHvqQZrEU1R6rYQmFTOe6Yemvt7T4DwNA2cLI3rcrYXkfXEpruhzpI9zbFURfRZbisL5r1N83UdZRcPddpy8vH5awZy1XtDoDZgAACBN6BloiWqmqIAIJli8jU0MTy03eiQ2bEAdy5WM6eV2SJ9nEq0iWae9QuWR9g85WApZesyT+0/+N2aX3fk5uBBbZvaQXWCS0vej/krkm9AIcfmimJ/0JqlaqquoIPhDls7xZM5UGFNPumxonjP9O+8Z6q8mZInvmr/R0O4T3ZNRoKdq3b5BKlHjRHDQuY5ODXBKzz3yFPxC5a+seMGUcB7117/nmzhoTUdeXL4BUCCS7ISoy76CPXK+/srq1yr8o24tJiX6YXNv+PBp39rUgMBMJVHMtbnNSSbvI9VWs/wZJnpUeJl5QOrW9GYjDbMmhyDOFgDVgNa02NZSugmZXZ0gh1r15nhuT/rbA0+r62L2OnJqoCNtuy1OI+SZDvz+Q3D6qW3WEKh31e8vwvAnk7sGOrzLbq/MRbPhRf43FYPQbCvfOFP7TMaKfkezXGHeL5P627JzGyo26l17DuiJNWRrbz7dzVIHG8bfEtMX1tDIddFXBGzu4c5hSZd9G59OyklISA4G16pt6vUkBKcUfWoSvrmyjTf7Q/STMgtQoH2VdDN3UDF7OFlEmUJCGkUc9LXBf+lwpHkvTaoDRjHgzMZXdP1D/RmyOzcSQk8/xNLZ+WIdw67CyTgyI+Z1MMa7gIWi91ugQa1EtAC0+VxnaoIE+6vIZsWtEImtMCOsjv7kjNBUtTdcYhUTcSbDWfIpJliMhP7SVunUOmkM0N7erZ4EvR6BaZ36cJmuZUQI='
            const userType = 2

            const params = {
                sdk: "8.0",
                entry: {
                    oneDrive: {
                        files: {},
                    }
                },
                authentication: {},
                messaging: {
                    origin: "http://localhost:80",
                    channelId: "27"
                },
                typesAndSources: {
                    mode: "files",
                    pivots: {
                        oneDrive: true,
                        recent: true,
                    },
                },
            };

            let win = null
            let port = null

            async function launchPicker(sameWindow) {

                //sameWindow.preventDefault();                

                const authToken = token

                const queryString = new URLSearchParams({
                    filePicker: JSON.stringify(params),
                });
                
                var url  = ''

                if(userType == 1){
                    url = combine(baseUrl, `_layouts/15/FilePicker.aspx?${queryString}`);
                } else {
                    url = baseUrl+`?${queryString}`;
                    console.log('Url is' + url)
                }
                //const url = combine(baseUrl, `_layouts/15/FilePicker.aspx?${queryString}`);

                if(sameWindow){
                    const iframe = document.getElementById("my-iframe");   
                    iframe.name = "frame";                 
                    iframe.setAttribute("height", "800");
                    iframe.setAttribute("width", "800");
                    document.body.appendChild(iframe);                    
                    const form = document.createElement("form");
                    form.setAttribute("action", url);                    
                    form.setAttribute("method", "POST");                    
                    document.body.appendChild(form);

                    const input = window.document.createElement("input");
                    input.setAttribute("type", "hidden")
                    input.setAttribute("name", "access_token");
                    input.setAttribute("value", authToken);
                    form.appendChild(input);
                    iframe.contentDocument.body.appendChild(form);
                    iframe.addEventListener('load', function(event) {   
                        form.submit();                        
                        const message = event.data;
                        if (message && message.type === "initialize" && message.channelId === params.messaging.channelId) {
                            const port = event.ports[0];
                            port.addEventListener("message", messageListener);
                            port.start();
                            port.postMessage({
                            type: "activate",
                            });
                        }
                      console.log('Form submitted!');
                    });                                    
                    } else {
                    win = window.open("", "Picker", "width=100,height=600")
                    const form = win.document.createElement("form");
                    form.setAttribute("action", url);
                    form.setAttribute("method", "POST");
                    win.document.body.append(form);

                    const input = win.document.createElement("input");
                    input.setAttribute("type", "hidden")
                    input.setAttribute("name", "access_token");
                    input.setAttribute("value", authToken);
                    form.appendChild(input);
                    form.submit();   
                    window.addEventListener("message", (event) => {

                    if (event.source) {

                        const message = event.data;

                        if (message.type === "initialize" && message.channelId === params.messaging.channelId) {

                            port = event.ports[0];

                            port.addEventListener("message", messageListener);

                            port.start();

                            port.postMessage({
                                type: "activate",
                            });
                        }
                    }
                });
                }
            }

                    async function messageListener(message) {
                        console.log(message);
                switch (message.data.type) {

                    case "notification":
                        console.log(`notification: ${message.data}`);
                        break;

                    case "command":

                        port.postMessage({
                            type: "acknowledge",
                            id: message.data.id,
                        });

                        const command = message.data.data;

                        switch (command.command) {

                            case "authenticate":


                               // Need to add refresh access token logic
                                const token = getToken()

                                if (typeof token !== "undefined" && token !== null) {

                                    port.postMessage({
                                        type: "result",
                                        id: message.data.id,
                                        data: {
                                            result: "token",
                                            token,
                                        }
                                    });

                                } else {
                                    console.error(`Could not get auth token for command: ${JSON.stringify(command)}`);
                                }

                                break;

                            case "close":

                                //win.close();
                                break;

                            case "pick":

                                console.log(`Picked: ${JSON.stringify(command)}`);

                                document.getElementById("pickedFiles").innerHTML = `<pre>${JSON.stringify(command, null, 2)}</pre>`;

                                port.postMessage({
                                    type: "result",
                                    id: message.data.id,
                                    data: {
                                        result: "success",
                                    },
                                });

                                win.close();

                                break;

                            default:

                                console.warn(`Unsupported command: ${JSON.stringify(command)}`, 2);

                                port.postMessage({
                                    result: "error",
                                    error: {
                                        code: "unsupportedCommand",
                                        message: command.command
                                    },
                                    isExpected: true,
                                });
                                break;
                        }

                        break;
                }
            }

            function getToken(){
                return token
            }

        </script>
        </head>
        <body>
            <button id="launchPicker">Launch Picker</button>
            <br />
            <div id="pickedFiles"></div>
            <button id="launchPickerinsamewindow">Launch Picker in Same window</button>
            <br />
            <div id="pickedFiles"></div>
            <div id="pickerDiv"></div>            
        </body>
        <script type="text/javascript">
            const launchPickerElement = document.getElementById("launchPicker");
            const launchPickerElementinWindow = document.getElementById("launchPickerinsamewindow");
            launchPickerElement.onclick = function() {
                        launchPicker(false)
            }
            launchPickerElementinWindow.onclick = function() {
                        launchPicker(true)
            } 
        </script>
    </html>

**Comment by patrick-rodgers** [comment]
What is the audience of the token you are getting in Postman? Also wondering why you aren't using one of the authentication options shown in the various samples to get the tokens?

My guess is that the token isn't valid for the resource.

**Comment by trickcharan** [comment]
Am sure the token is valid, because when I use the same token with below code it is working
win = window.open("", "Picker", "width=800,height=600")

But if I change width to 200 from 800 it stucks. Same I have shown in the video by resizing the window.

FYI l: Am working on an application where am not supposed to use MSAL login, instead i should use OAuth.2.0 url to get tokens. So using postman to generate token and same token is used to load v8 picker.

**Comment by trickcharan** [comment]
Any update on this or still need any information?

**Comment by ThomasMichon** [comment]
The `setupTimeout` issue you are seeing occurs when the File Picker frame does not receive the `'activate'` message from your host app within 40 seconds after it starts booting. This usually occurs if the host doesn't receive or correctly handle the `'initialize'` message sent from the Picker frame.

I would recommend sticking a debug breakpoint here:
```js
                window.addEventListener("message", (event) => {

                // debugger; <-- Breakpoint here!

                if (event.source) {

                    const message = event.data;

                    if (message.type === "initialize" && message.channelId === params.messaging.channelId) {

                        // <-- Validate that you get here!

                        port = event.ports[0];

                        port.addEventListener("message", messageListener);

                        port.start();

                        port.postMessage({
                            type: "activate",
                        });
                    }
                }
            });
```

If your `message` event listener does not get hit at all, then it could be for one of two reasons:
1. The `origin` passed to the Picker options is not an exact match for what the browser expects. I recommend sending `origin: location.origin` instead of hard-coding any specific value
  OR
2. The File Picker can't actually "see" your host window due to browser security boundaries. If updating `origin` doesn't fix the issue, you can try using the `identify-parent` flow demonstrated in this JSFiddle:
  https://jsfiddle.net/ThomasMichon/Lxje15bz/
  The idea is that while the Picker is continuing to load, your host app sends a message with `type: 'identify-parent'` on an interval, and once the Picker receives it then it will send the `'initialize'` message to you.

**Comment by JCrew0** [comment]
@trickcharan I am going to close this issue given the inactivity. Please reach back out on this thread if you are still running into the issue. Thanks!
