### ISSUE TITLE
FilePicker v8 requires multiple clicks to select 'places' when in compact mode

### ISSUE THREAD

**Issue by jonathon-love** [OneDrive/samples#32]
When the filepicker is in "compact mode" (i.e. the the width is small, and rather than displaying the 'places' to the left, and the 'directory listing' to the right, it only displays one at a time.) it can require multiple clicks to choose a new 'place'. see the following video:

https://youtu.be/Uy8hyXxq3ds

it always requires two clicks to access SharePoint places (the first account demoed in the above video), however the situation is worse with the consumer onedrive.live.com personal accounts (the second account demoed) ... you can see that it will not navigate to 'My Files' at all, until you first navigate to 'Photos' and then back again.

i don't believe this behaviour is a problem with my implementation, because when not running in "compact mode" it all works fine.

with thanks

**Comment by ThomasMichon** [comment]
@jonathon-love good find! This is a fairly-recent regression in the Picker's behavior. We will have a fix deployed in the next coupld of weeks.
