### ISSUE TITLE
How to migrate onedrive filpicker from onedrive7.2 to 8.0

### ISSUE THREAD

**Issue by geetharamu** [OneDrive/samples#33]
We are using javascript onedrive filepicker 7.2 in our application.
https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online

If we need to migrate from onedrive v7.2 to v8, what are the steps need to follow

**Comment by patrick-rodgers** [comment]
There isn't a migration guide as such since they are two different technologies. You can [follow the docs](https://aka.ms/onedrive/file-picker) to understand how to setup the v8 picker.
