### ISSUE TITLE
OneDrive File Picker v8 - Opening documents of shared team requires 2 clicks

### ISSUE THREAD

**Issue by LukaszGawlikBridge** [OneDrive/samples#38]
**Describe the bug**
First time opening documents of shared team requires 2 clicks. Later it is working OK, documents are opened after 1 click. 

**To Reproduce**
Please see attached movie:

https://user-images.githubusercontent.com/128077511/230378693-60349ad9-25c5-49a9-b69b-ed282438550d.mp4

**Expected behavior**
Shared team should be opened after 1 click.

**Comment by patrick-rodgers** [comment]
Similar to #32.

**Comment by ntennant4** [comment]
This should now be resolved, closing the issue, let us know if you're still seeing the issue
