### ISSUE TITLE
OneDrive File Picker v8 - there is https://graph.microsoft.com/beta/ used, beta should not be used for production application

### ISSUE THREAD

**Issue by LukaszGawlikBridge** [OneDrive/samples#39]
**Describe the bug**
When accessing documents of shared team, **graph beta** is used (https://graph.microsoft.com/beta/).
According to https://learn.microsoft.com/en-us/graph/use-the-api, beta version should not be used for production application.

![image](https://user-images.githubusercontent.com/128077511/230382275-19fb8cf0-a8b0-4b5f-8cc7-c4a44656bcc9.png)

![image](https://user-images.githubusercontent.com/128077511/230383789-4178a814-157c-4a87-a805-d75f84e16333.png)

**Expected behavior**
Graph v1.0 should be used

**Comment by patrick-rodgers** [comment]
Thank you for your feedback, the internal implementation of the control is determined by the engineering team in partnership with other teams across the company.

**Comment by LukaszGawlikBridge** [comment]
@patrick-rodgers Thank you for the answer. Just for confirmation, graph beta version is used, but as I understand 
it is guaranteed that Picker is stable solution and it can be used in production applications, please confirm?
