### ISSUE TITLE
OneDrive File Picker v8 - bug in searching related to cleaning Searching criteria

### ISSUE THREAD

**Issue by LukaszGawlikBridge** [OneDrive/samples#40]
**Describe the bug**
In searching functionality, there is bug related to cleaning Searching criteria.

**To Reproduce**

1. Search using some text, press Enter -> filter is applied
2. Clear searching criteria by "x" sign -> text is removed from Search field, but file list is not refreshed, they are still filtered
3. Press Enter -> empty string "" is used for searching, so nothing is displayed
4. You have to click for example "My files" to refresh the list of files, and correct the problem.

Please see the movie:

https://user-images.githubusercontent.com/128077511/230386857-9e319621-a84b-4a27-ae6b-f8fa455b8f8a.mp4

**Expected behavior**
After cleaning the searching criteria by "x" and pressing Enter, the list of files should be refreshed, and files should be displayed without any filtering (there are not any searching criteria).

**Comment by ntennant4** [comment]
This should now be resolved, closing the issue, let us know if you're still seeing the issue
