### ISSUE TITLE
OneDrive File Picker v8 - Chrome browser v112 - There are errors with type Refused to get unsafe header...

### ISSUE THREAD

**Issue by LukaszGawlikBridge** [OneDrive/samples#41]
**Describe the bug**
Chrome Version 112.0.5615.50 (Official Build) (64-bit), in Developer Tools opened on File Picker there are errors with type "Refused to get unsafe header..."
![image](https://user-images.githubusercontent.com/128077511/230459988-c151f4fc-efc6-4e06-9e87-5ec7c05467e5.png)

Can these errors cause any problems with File Picker?

**Expected behavior**
There should not be this kind of errors

**Comment by patrick-rodgers** [comment]
This doesn't seem like you are reporting an error or problem with the control. Going to close this issue, if you determine there is a problem please open a new issue and reference this one, providing more details on the issue you are facing. Thanks!
