### ISSUE TITLE
How to get base url for personal accounts - picker v8

### ISSUE THREAD

**Issue by oreoluwa-bs** [OneDrive/samples#43]
Hello,

**Describe the bug**
With reference to this #21 could not get the web url from the `https://graph.microsoft.com/v1.0/me/drive` but I found it in `https://graph.microsoft.com/v1.0/me/drive/root`. The web url gotten from this endpoint for a business account is "{tenant}.sharepoint.com" but for personal accounts it is https://onedrive.live.com/?cid=xxxxx.

The issue is when the base url is combined with "_layouts/15/FilePicker.aspx" personal accounts return an item not found view, for business account it seems to work fine

**To Reproduce**
- Make a oauth request with msal using the '/common' authority - with the scope "https://graph.microsoft.com/.default" (do not pass the base url at this point)
- Acquire token using the login functions
- Make a request to `https://graph.microsoft.com/v1.0/me/drive/root` and parse web url to get the base url
- Determine if a new token should be generated if the user is a business account and pass the base url gotten from previous step
- Combine the base url with "_layouts/15/FilePicker.aspx" and trigger popup for picker

**Expected behavior**
Expected a picker screen for personal one drive accounts instead received item not found.

**Screenshots**
<img width="799" alt="Screenshot 2023-04-12 at 11 25 01" src="https://user-images.githubusercontent.com/46888096/231431432-2fe102ed-65e0-45c8-be73-ee0288e24cc8.png">

**Details**
I am trying to create a space where users can open their one drive and share links to files with me via the file picker v8

Thank you.

**Comment by patrick-rodgers** [comment]
The base URL for the consumer picker is `https://onedrive.live.com/picker`. It is [shown in this sample](https://github.com/OneDrive/samples/tree/master/samples/file-picking/javascript-basic-consumer#onedrive-consumer-configuration) but looks like it is missing from the main docs page, will get that updated.

**Comment by sebastianstampfel** [comment]
@patrick-rodgers if i understand correctly we need two distinct URLs for the picker, `https://onedrive.live.com/picker` for personal accounts and `https://<tenant-name>.sharepoint.com/_layouts/15/FilePicker.aspx` for organizational accounts. I dug deep in the docs but I could not figure out a way of knowing wether or not an account is a personal or organizational account after triggering the login with msal-browser.
Also the samples don't seem to cover that issue (unless I missed something).
How can we, using msal-browser, figure out if an account is personal or organizational? And how can we retrieve the tenant name using msal-browser?
