### ISSUE TITLE
Cannot find module '@pnp/picker-sdk' or its corresponding type declarations.

### ISSUE THREAD

**Issue by nihilent-kamat** [OneDrive/samples#44]
**Describe the bug**
While trying to implement the sample for typescript it is keep on showing that module is not fount although it is there in the node module.

**To Reproduce**
first what i did is, just tried to run the sample code after npm install it is showing the error then ii imported the files in my project and the error is still present

**Expected behavior**
It is supposed to get imported in the ts file for implementation

**Screenshots**
![image](https://user-images.githubusercontent.com/129716631/231754092-61b40bb8-6b12-4a8a-95a4-8c59a21fa202.png)

Please HElp me resolve this issue. I have been trying to fix this since days i have tried many a things.

**Comment by patrick-rodgers** [comment]
Did you locally build the [solution as mentioned here](https://github.com/OneDrive/samples/tree/master/samples/file-picking/typescript-sdk#build-the-example-sdk)?

**Comment by nicolasiscoding** [comment]
+1 on this. We ended up having to do some weird build pipeline to use this in staging and soon to be production. Are there any plans to make this a package in npm or equivalent and save us the build step?

**Comment by nihilent-kamat** [comment]
@patrick-rodgers i did as solution mentioned and it worked, but still facing some other issues which are i guess related to typescript. Because i am trying to implement this in angular 7 which supports typescript 3.2 max. Thank you for responding. any suggetion/solution for implementing the same in angular 7?
