### ISSUE TITLE
Teams Webclient vs Teams Desktop Client

### ISSUE THREAD

**Issue by RussatCBDigital** [OneDrive/samples#46]
We are currently implementing the OneDriveFilePicker v8 in a custom Teams tab application that integrates with a partner 3rd party e signature platform. When using from the web client the picker behaves as expected. However, when same code is tested in the desktop client it seems that the picker app is blocked from loading. Can the developers please verify that the opening of the OneDriveFilePicker is possible in the desktop client (similar to "Attach cloud files" from chat) and if so can someone point to a sample configuration that might point us in a direction to resolve this issue?

**Comment by patrick-rodgers** [comment]
Can you share your config file (obfuscating any private details)?

**Comment by RussatCBDigital** [comment]
Here is my picker config.  Thanks
{
    sdk: "8.0",
    entry: {
        oneDrive: {
        },
    },
    authentication: {},
    messaging: {
        origin: "<app url>",
        channelId: "27"
    },   
    typesAndSources: {
        mode: "files",
        pivots: {
            sharedLibraries: true, 
            recent: true,
            oneDrive: true,
        },
    },
}

**Comment by patrick-rodgers** [comment]
I am currently not able to duplicate. Are you sending the authentication token in the intitial POST request to the form [as shown in the example](https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/?view=odsp-graph-online#initiate-the-picker)? If you don't the picker won't load in an iframe.

**Comment by patrick-rodgers** [comment]
That SDK is meant as an example, not necessarily for use directly in production code as-is and not something we are publishing/supporting independently from the picker.

If the authentication is set correctly and you aren't seeing the error "Could not gain auth token in form setup." then that part should be OK. Have you tried without the SDK, more inline with the [basic example](https://github.com/OneDrive/samples/blob/master/samples/file-picking/javascript-basic/index.html)?

What kind of thing did you create? Teams App, SPFx? Are you able to share your solution, right now I am not even sure what you've built. Where is the picker being used? Does the thing you built support popups within the desktop client or are they possibly being blocked?

**Comment by patrick-rodgers** [comment]
Closing as resolved through the new [Teams Picker sample](https://github.com/OneDrive/samples/tree/master/samples/file-picking/teams-picker).
