### ISSUE TITLE
OneDrive File Picker v8 - Production integration has stopped working and raising a 404 error

### ISSUE THREAD

**Issue by tomagendium** [OneDrive/samples#47]
Hi,

We've had a working integration in our product using the OneDrive File Picker v8 and have had several customers using it without issue. In the last few weeks however, we got reports that it was no longer working, and indeed our own testing has shown that it's now generating some errors in the browser console after the authentication stage - namely a POST 404ing, followed by many JS errors from within the picker frame. I can see that some content has loaded inside the picker frame, but at that point it fails and displays nothing.

The source of the request that 404s is interestingly in a file path dated June 2nd which would line up to when this started happening.

I've had a look over the documentation in case something had changed about how this is supposed to be implemented, but I haven't found anything, and so we're turning here for help. One note related to the picker config below - as said this was working with the below config, but I did try many variations on the `entry` field (full url, specifying folders etc.) and all result in the same error. Real values replaced with customer_ variables below.

**Picker configuration:**
```
const params = {
  sdk: '8.0',
  entry: {
    sharePoint: {
      byPath: {
        web: `/sites/customer_site_name`
      }
    }
  },
  authentication: {},
  messaging: {
    origin: document.location.origin,
    channelId: channelId
  },
  typesAndSources: {
    mode: 'files',
    pivots: {
      recent: false,
      oneDrive: false,
      sharedLibraries: false
    }
  },
  selection: {
    mode: 'multiple'
  }
};
```

**404 error**
- 404ing request: `POST https://customer_tenant.sharepoint.com/_api/web/GetListUsingPath(DecodedUrl=@a1)/RenderListDataAsStream?@a1=%27%2Fsites%2Fcustomer_site_name%27&RootFolder=%2Fsites%2Fcustomer_site_name&TryNewExperienceSingle=TRUE`
- Raised from: `https://res-1.cdn.office.net/files/odsp-web-prod_2023-06-02.001/spofilepickerwebpack/plt.listviewdataprefetch.js`

**JS errors**
<img width="774" alt="od_error" src="https://github.com/OneDrive/samples/assets/50625328/ffedf7f6-436c-485d-9136-5a352503edeb">

**Comment by patrick-rodgers** [comment]
I am not able to duplicate this behavior. My samples are all working as expected. It is possible there was a regression that is now fixed. Are you still seeing problems?

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
