### ISSUE TITLE
Using MSAL without Cookies: Acquiring Tokens and Authentication Flows with Existing Microsoft Graph Tokens

### ISSUE THREAD

**Issue by trickcharan** [OneDrive/samples#48]
I have successfully authenticated with Microsoft for Microsoft Graph and have obtained a Microsoft Graph access token and refresh token. However, my scenario requires using the MSAL library without relying on cookies for authentication. I would like to know if it is possible to utilize MSAL to acquire tokens and perform authentication flows using the existing Microsoft Graph access token and refresh token, without requiring cookies. Any guidance or insights on how to achieve this would be greatly appreciated. Thank you!

**Comment by patrick-rodgers** [comment]
This isn't a general help forum and is focused on supporting the samples listed in the repo. For general Graph questions please try: https://developer.microsoft.com/en-us/graph/support
