### ISSUE TITLE
SharePoint CSOM rate limit code is slow with .net frame work console application and rate limit headers are not appearing in .net framework console application

### ISSUE THREAD

**Issue by manjunathreddy1** [OneDrive/samples#50]
**Describe the bug**
Sample code of SharePoint CSOM rate limit is working fine with .net 7 console application (completing 700+ csom requests with 5 threads) and it is slow in .net framework application (completing 200+ csom requests with 5 threads). Also rete limit headers are not appearing in .net framework console app. So please help to get clarification for this issue.

**To Reproduce**
Steps to reproduce the behavior: Add the code in the project (samples-master\scenarios\throttling-ratelimit-handling\RateLimitDemo) to .net framework console application

**Expected behavior**
Rate limit headers are not appearing when rate limit sample code is added to .net framework console application. If this is the expected behavior please suggest work around solution for this.

**Screenshots**
.net 7 console app
![image](https://github.com/OneDrive/samples/assets/265137/bcab76e6-8925-4866-a76a-b2430cd5d312)
.net framework console app
![image](https://github.com/OneDrive/samples/assets/265137/7e7f322f-6b83-456d-bdce-66008ccfd33c)

**Comment by JCrew0** [comment]
Hey @manjunathreddy1, I'm going through and looking at some of the older issues. Did anyone ever address this or did you come up with a solution? If not, I can see if there's anyone that can update the .net example.
