### ISSUE TITLE
Sharepoint Entry Strings Issues

### ISSUE THREAD

**Issue by nicolasiscoding** [OneDrive/samples#53]
**Describe the bug**
I am trying to specify an entrypoint into Sharepoint but I am unable to figure out how to format the strings. Let's say I have this path in Sharepoint (excuse my highlighting and anonymization skills) 

**For this directory:**
![image](https://github.com/OneDrive/samples/assets/9352910/1c9e2469-f36b-4902-aeb8-7eec3db0cc1b)

**How should my Sharepoint Entry look in the options? I've tried a few things including some of what I used below (Note, this is my options but I am programmatically setting it)**
![image](https://github.com/OneDrive/samples/assets/9352910/4ccb73c7-69d3-4535-90e6-d58c2a6b6a74)
![image](https://github.com/OneDrive/samples/assets/9352910/13851de5-8129-455b-a355-26f3ea889342)

**This is what I am seeing on my end and it works inconsistently with other paths:**
![image](https://github.com/OneDrive/samples/assets/9352910/69f1049a-5685-46e6-b193-29af01c84e0a)

For my application's user experience, the idea is for someone to set this path in the UI and I add it to the options for the initial entry point.

Thank you in advance!

**Comment by patrick-rodgers** [comment]
I have added a [sample for you](https://github.com/OneDrive/samples/blob/master/samples/file-picking/example-picker-configs/folder-path.json) showing how to address a folder path. Note you might need to review the permissions the app is consented to include additional scopes depending on the site(s) you are targeting. Delegated Sites.Read.All or Files.Read.All may be required.

**Comment by nicolasiscoding** [comment]
Thank you @patrick-rodgers !!

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
