### ISSUE TITLE
FileBrowser: Theme support? 

### ISSUE THREAD

**Issue by ottD** [OneDrive/samples#54]
**Is your feature request related to a problem? Please describe.**
I've been using the [FileBrowser component](https://learn.microsoft.com/en-us/onedrive/developer/controls/file-browser/?view=odsp-graph-online) and find it frustrating that there does not seem to be a documented way to set the Theme. There is nothing in the Browser Configuration object and passing additional query string parameters such as `&theme=dark` does not work. 

**Describe the solution you'd like**
I'd like to know whether and how the FileBrowser can be rendered using a different Theme. Either by passing the Theme in the Browser Configuration options or through an additional query string parameter. 

**Describe alternatives you've considered**
I've tried adding  additional query string parameters such as. `&theme=dark`. 

**Additional context**
The code samples and File Browser documentation do not show how to render the FileBrowser with a different Theme. Can the documentation or samples be updated to cover this scenario?

**Comment by patrick-rodgers** [comment]
Thank you for the question, we've logged it with the engineering team.

**Comment by ottD** [comment]
@patrick-rodgers Do you have any update regarding theme support in the File Browser component? Thanks

**Comment by JCrew0** [comment]
Updated the docs!

**Comment by ottD** [comment]
Thanks for updating the docs! I can confirm that adding the `theme` string to the file browser configuration JSON works as expected 👍

**Comment by rgcircum** [comment]
@ottD Thanks for updatting. 
Is possible to pass SharePoint theme name to pass correct color sheme (custom theme), not default SP Theme ?

PS : it's work also on filePicker ;) (doc not updated)

**Comment by JCrew0** [comment]
@rgcircum You'd have to pass it as a theme object. However, I haven't added any documentation for that yet. I'll add some in the future, but it might take some time.

Yeah, myself or one of my team members will be editing the file picker docs.

I can ping you here once we update the documentations for custom themes and for the file picker.

**Comment by rgcircum** [comment]
@JCrew0 nice! it's work perfectly !!!

**Comment by MacroView-Kieran** [comment]
The 'default' | 'dark' | 'lists' themes seem to work as expected.
The 'teams' | 'teams-default' | 'teams-dark' | 'teams-contrast' do not seem to work. 

Is there additional config parameters or query string parameters to enable the Teams specific theming?
