### ISSUE TITLE
File Browser: Browser Configuration Schema in documentation differs from code sample

### ISSUE THREAD

**Issue by ottD** [OneDrive/samples#56]
**Issue description**
The [File Browser configuration schema ](https://learn.microsoft.com/en-us/onedrive/developer/controls/file-browser/v8-schema?view=odsp-graph-online) in the documentation differs from the schema used in the [typescript-react sample.](https://github.com/OneDrive/samples/blob/master/samples/file-browsing/typescript-react/src/types.ts). In the documentation, the `entry ` parameter includes the authentication, breadcrumb, commands etc. parameters whereas in the actual code sample these are separate entries in the JSON schema. 

Also note, that the [link ](https://aka.ms/OneDrive/samples/file-browsing)to the code sample from the [documentation page](https://learn.microsoft.com/en-us/onedrive/developer/controls/file-browser/?view=odsp-graph-online) is broken. 

**Steps To Reproduce**
Inspect the Browser Configuration schema in the documentation and compare it to the schema used in the `typescript-react` File Browser sample code. Note that in the documentation the `authentication `and `breadcrumb `parameter are under the `entry `parameter whereas this is not the case in the code sample where they are at the same level as the `entry `parameter. It looks like the Browser Configuration Schema in the documentation is not correct. 

**Expected behavior**
Code sample corresponds to documentation and documentation links correctly to sample repo. 

**Screenshots**
code sample:
<img width="313" alt="image" src="https://github.com/OneDrive/samples/assets/33263347/2229026b-6a75-45b0-90bc-2fc6ed4f2be7">

Schema used in documentation:

 ```
entry: {
        sharePoint?: {
            byPath?: {
                web?: string;
                list?: string;
                folder?: string;
                fallbackToRoot?: boolean;
            };
        };
 
        oneDrive?: {
            files?: {
                folder?: string;
                fallbackToRoot?: boolean;
            };
        };
        authentication: {
            claimsChallenge?: {
                enabled?: boolean;
            };
        };
        breadcrumb?: {

            root?: {
                sharePoint?: {
                    byPath?: {
                        web?: string;
                        list?: string;
                        folder?: string;
                    };
                };
            };
        };
```

**Comment by JCrew0** [comment]
@ottD Sorry for the delay here as well, hope this hasn't been blocking you! I've logged this internally for myself and will go make edits when I get a chance. Thanks!

**Comment by JCrew0** [comment]
I have this PR that I've been trying to get merged for a bit: https://github.com/OneDrive/onedrive-api-docs/pull/1762
