### ISSUE TITLE
UnableToDetermineOneDriveLocation

### ISSUE THREAD

**Issue by schnoberts1** [OneDrive/samples#60]
Hi, 

I guess this could be less a bug request and more a request for insights. I want to point the javascript (basic) one drive file picker at another users OneDrive (content of which is shared). I can access the relevant URL via the browser (e.g. https://blah-my.sharepoint.com/personal/user_domain_name/_layouts/15/filepicker.aspx?. However, this doesn't seem to work as well via the file picker API. Note: the user which has permissions to access this OneDrive doesn't have their own OneDrive. 

I tried putting the user section of the URL in baseurl, I also tried it in the entry point in the query config. 

In each case I get UnableToDetermineOneDriveLocation. I can't find any documentation via google or learn.microsoft.com for this error.

Note: I can do what I am trying to achieve above using .NET Core and C# and the app registrations are the same in the appropriate places so I am assuming there is missing config magic or the picker doesn't support this type of access.

**Comment by nicolasiscoding** [comment]
Hey @schnoberts1 I just had a similar issue. Patrick went in and added some nice examples but tagging this for reference (if this is helpful)

https://github.com/OneDrive/samples/issues/53

**Comment by schnoberts1** [comment]
Thanks @nicolasiscoding . I will take a look.

**Comment by JCrew0** [comment]
@schnoberts1 @nicolasiscoding We've updated our error code reporting in this scenario, which will rollout later this week. Can you try again sometime next week?

**Comment by nicolasiscoding** [comment]
We ended up writing our own implementation using the graph api due to
issues with docsets. For my next client onboarding, will give this a whirl.

**Comment by JCrew0** [comment]
Closing for now, please mention me and/or re-open if this is not fixed.
