### ISSUE TITLE
How to pick file from frontend and download that file from python backend

### ISSUE THREAD

**Issue by aravindarc** [OneDrive/samples#62]
I used the samples to pick the file in the frontend. There are some details of the picked file. I want to send these details to the backend and download the file. Is there a way to do this.

**Comment by JCrew0** [comment]
@aravindarc You'll want to follow the instructions here to download the item: https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content?view=odsp-graph-online.

In the File-Picker response, you'll see `siteId` and `listItemUniqueId`. You can map those to `site-id` and `item-id` respectively in this request format: `GET /sites/{siteId}/drive/items/{item-id}/content`.

Make sure that you provide a proper graph auth token as well. 

Hope that helps!
