### ISSUE TITLE
Specifying sharedLibraries = true in typesAndSources.pivots generates a security related exception

### ISSUE THREAD

**Issue by chartnado-brian-haas** [OneDrive/samples#7]
We want to allow users to pick files from SharePoint and Teams sites/drives as well as their personal OneDrive folder.  The documentation indicates that this should be performed by specifying sharedLibraries = true as described in the issue summary.  When the picker is presented, the user's list of SharePoint and Teams sites shows correctly on the left hand side of the picker.  However, as soon as a SharePoint site is selected on the left hand side in order to view that site's files, the following message is presented to the user:

Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown.

To reproduce this error:

1. Start with the basic js demo located in samples/file-picking/javascript-basic
2. In auth.js, specify the tenant id as described in the documentation
3. In index.html, set the baseUrl to the user's base OneDrive path as described in the documentation (for example "https://XXXXXXXX-my.sharepoint.com")
4. In index.html, at line 38, add the property sharedLibraries: true to the pivots property

The expected behavior is that the user can navigate SharePoint/Teams sites/drives as well as their own OneDrive files.  The actual behavior is that a user can browse their own files, but an exception is presented when attempting to view SharePoint/Teams files.

![onedrive](https://user-images.githubusercontent.com/39094065/177808570-bf2ae451-e3b8-4b28-9e92-5cdef744b529.png)

**Comment by chartnado-brian-haas** [comment]
You are correct.  I need to provide tokens for https://tenant.sharepoint.com and https://tenant-my.sharepoint.com.

I'm not sure why the basic javascript demo doesn't work for me.  It is requesting tokens for the 2 separate resources, but the same token is returned as a result.  I can see personal files only with the demo, and not SharePoint site files.

We use msal.net and not msal.js in our solution, and the tokens we get from that are different between OneDrive and SharePoint.  Consequently, I now have a working solution in our application but the demo still doesn't work for me.

Thanks!

**Comment by capedrolima** [comment]
> Glad you got it working, we'll have to review the demo code and see what might be wrong there. Thanks!

Hi @patrick-rodgers  do you have any update about it? We tried to use the javascript sample but had the same problem. We are trying to manage it but have had no luck. 

![11-30-2022 (10-26-57)](https://user-images.githubusercontent.com/50597814/204839847-37b4f14a-437a-4291-a908-e86a1bf96a72.gif)
![11-30-2022 (10-26-17)](https://user-images.githubusercontent.com/50597814/204839855-497bfe85-9be1-4e40-99d6-a773deb17bb8.gif)
