### ISSUE TITLE
Teams specific themes not working.

### ISSUE THREAD

**Issue by MrKSchmitz** [OneDrive/samples#74]
Theme support for the [FileBrowser component](https://learn.microsoft.com/en-us/onedrive/developer/controls/file-browser/?view=odsp-graph-online) was added/documented in ticket #54. 
However the theme values 'teams' | 'teams-default' | 'teams-dark' | 'teams-contrast' do not work.
'default' | 'dark' | 'lists' seem to work as expected.

To reproduce; attempt to use the teams specific themes in the Browser Configuration.

Expected behavior; teams specific themes should follow the teams color schemes.

**Comment by JCrew0** [comment]
@MrKSchmitz Just tested this on my end and can confirm they aren't working. I contacted the owner to see if this is a regression or if these themes aren't publicly supported yet. Will let you know

**Comment by ThomasMichon** [comment]
I apologize, this is a documentation mistake. The File Browser component only supports the Teams themes when consumed *directly* via Teams as our integrated "Files" apps, notably the "OneDrive" app in the left rail and the Files tab of a channel.
