### ISSUE TITLE
Example using Picker v8 with personal Microsoft accounts

### ISSUE THREAD

**Issue by jviney** [OneDrive/samples#8]
Is there an example of using OneDrive Picker v8 with personal Microsoft accounts? All the examples I can see use business accounts.

**Comment by patrick-rodgers** [comment]
Just added a [new basic sample](https://github.com/OneDrive/samples/tree/master/samples/file-picking/javascript-basic-consumer) showing how to use the picker with consumer (personal accounts).

**Comment by matthewhampton** [comment]
> > Just added a [new basic sample](https://github.com/OneDrive/samples/tree/master/samples/file-picking/javascript-basic-consumer) showing how to use the picker with consumer (personal accounts).
> 
> Hi @patrick-rodgers ... Please forgive me if this is something obvious (or in the wrong place), but I am struggling to get this to work with my app...
> 
> I get an error trying to get that "onedrive.readwrite" scope for the token saying that it "is not configured for this tenant" - but I can't figure out how to configure it! It doesn't show up as one of the API options on my app registration. Do you have any hints for me on how to troubleshoot?
> 
> Thanks!

Actually - I think it was the "authority" that I was missing! It was obvious! Thanks...
